version: '3.8'

services:
  ui_service:
    build: ./ui_service
    ports:
      - "5005:5005"
    depends_on:
      - api_gateway

  api_gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth_service
      - transcription_service
      - analysis_service
      - storage_service
      - report_service
      - redis

  auth_service:
    build: ./auth_service
    ports:
      - "5000:5000"

  transcription_service:
    build: ./transcription_service
    ports:
      - "5001:5001"

  analysis_service:
    build: ./analysis_service
    ports:
      - "5002:5002"

  storage_service:
    build: ./storage_service
    ports:
      - "5003:5003"
    volumes:
      - storage_data:/data

  report_service:
    build: ./report_service
    ports:
      - "5004:5004"
    volumes:
      - report_data:/app/reports

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  storage_data:
  report_data:
